package com.javarush.ua.marzhiievskyi.utils.gettingParameters;

public class GettingConstants {

    private String ORGANISM_PARAMETERS_FILE_PATH ;
    private String GAME_ISLAND_PARAMETERS_FILE_PATH;
    private String ORGANISM_EAT_CHANCE_FILE_PATH ;
    private double WEIGHT_LOSE_PER_ACTION ;
    private int CHANCE_TO_BIRTH_CHILD;
    private int CHANCE_TO_BIRTH_CHILD_FOR_PLANTS;
    private int COUNT_OF_DESCENDANTS_FOR_PLANTS;
    private int COUNT_OF_DESCENDANTS_FOR_ANIMALS;

    public String getORGANISM_PARAMETERS_FILE_PATH() {
        return ORGANISM_PARAMETERS_FILE_PATH;
    }

    public void setORGANISM_PARAMETERS_FILE_PATH(String ORGANISM_PARAMETERS_FILE_PATH) {
        this.ORGANISM_PARAMETERS_FILE_PATH = ORGANISM_PARAMETERS_FILE_PATH;
    }

    public String getGAME_ISLAND_PARAMETERS_FILE_PATH() {
        return GAME_ISLAND_PARAMETERS_FILE_PATH;
    }

    public void setGAME_ISLAND_PARAMETERS_FILE_PATH(String GAME_ISLAND_PARAMETERS_FILE_PATH) {
        this.GAME_ISLAND_PARAMETERS_FILE_PATH = GAME_ISLAND_PARAMETERS_FILE_PATH;
    }

    public String getORGANISM_EAT_CHANCE_FILE_PATH() {
        return ORGANISM_EAT_CHANCE_FILE_PATH;
    }

    public void setORGANISM_EAT_CHANCE_FILE_PATH(String ORGANISM_EAT_CHANCE_FILE_PATH) {
        this.ORGANISM_EAT_CHANCE_FILE_PATH = ORGANISM_EAT_CHANCE_FILE_PATH;
    }

    public double getWEIGHT_LOSE_PER_ACTION() {
        return WEIGHT_LOSE_PER_ACTION;
    }

    public void setWEIGHT_LOSE_PER_ACTION(double WEIGHT_LOSE_PER_ACTION) {
        this.WEIGHT_LOSE_PER_ACTION = WEIGHT_LOSE_PER_ACTION;
    }

    public int getCHANCE_TO_BIRTH_CHILD() {
        return CHANCE_TO_BIRTH_CHILD;
    }

    public void setCHANCE_TO_BIRTH_CHILD(int CHANCE_TO_BIRTH_CHILD) {
        this.CHANCE_TO_BIRTH_CHILD = CHANCE_TO_BIRTH_CHILD;
    }

    public int getCHANCE_TO_BIRTH_CHILD_FOR_PLANTS() {
        return CHANCE_TO_BIRTH_CHILD_FOR_PLANTS;
    }

    public void setCHANCE_TO_BIRTH_CHILD_FOR_PLANTS(int CHANCE_TO_BIRTH_CHILD_FOR_PLANTS) {
        this.CHANCE_TO_BIRTH_CHILD_FOR_PLANTS = CHANCE_TO_BIRTH_CHILD_FOR_PLANTS;
    }

    public int getCOUNT_OF_DESCENDANTS_FOR_PLANTS() {
        return COUNT_OF_DESCENDANTS_FOR_PLANTS;
    }

    public void setCOUNT_OF_DESCENDANTS_FOR_PLANTS(int COUNT_OF_DESCENDANTS_FOR_PLANTS) {
        this.COUNT_OF_DESCENDANTS_FOR_PLANTS = COUNT_OF_DESCENDANTS_FOR_PLANTS;
    }

    public int getCOUNT_OF_DESCENDANTS_FOR_ANIMALS() {
        return COUNT_OF_DESCENDANTS_FOR_ANIMALS;
    }

    public void setCOUNT_OF_DESCENDANTS_FOR_ANIMALS(int COUNT_OF_DESCENDANTS_FOR_ANIMALS) {
        this.COUNT_OF_DESCENDANTS_FOR_ANIMALS = COUNT_OF_DESCENDANTS_FOR_ANIMALS;
    }
}
